using System;

namespace SBPR.Niflheim.HomesteadStones.Domain
{
    // FIX R3 (event-time Homestead Stone realization) — engine-free lifecycle decisions.
    //
    // WHY THIS REPLACES HomesteadHeadlessSeat
    // R1/R2 reconstructed a host's footprint and leveled surface from generic persisted ZDO pivots on a
    // headless dedicated server. Fresh review (PR #323) rejected that as unsound: a ZDO transform pivot is
    // neither a collider bound nor a terrain sample, the creator==0-in-radius harvest also swept in the
    // LocationProxy / zone-control / vegetation, and the tests only exercised synthetic pre-labelled points.
    //
    // The correct seam is EVENT-TIME. Vanilla realizes a fresh zone via
    // `ZoneSystem.SpawnZone(Ghost|Full)` -> `PlaceLocations(zoneID, .., hmap, .., mode, spawnedObjects)`
    // (decompiled vanilla, base-game RE per ADR-0001). Inside `PlaceLocations` the host's own ZNetView
    // children are freshly `Instantiate`d at their final world positions with real colliders, the live
    // `Heightmap` is passed in, and the location's `TerrainModifier`/`TerrainComp` leveling has been applied.
    // Only AFTER `PlaceLocations` returns does `SpawnZone` destroy the ghost temp objects (Ghost mode). A
    // Harmony POSTFIX on `PlaceLocations` therefore observes the real geometry, on BOTH a listen server
    // (Full) and a headless dedicated server (Ghost), while it still exists — exactly the window R1/R2 tried
    // to reconstruct after the fact. ZDO persistence is retained by bracketing the additive Stone's creation
    // in `ZNetView.StartGhostInit()`/`FinishGhostInit()` in Ghost mode, mirroring how vanilla persists the
    // host structure ZDOs that survive the temp-object destruction.
    //
    // `PlaceLocations` also fires EXACTLY ONCE per zone for the lifetime of a world (vanilla guards the body
    // with `!value.m_placed`, and `SpawnZone` guards on `!IsZoneGenerated(zoneID)` and calls
    // `SetZoneGenerated` afterwards). So the fresh-creation event is one-shot: a restart re-loads the
    // persisted Stone ZDO instead and the postfix never re-fires for that zone. An already-generated host
    // that has NO Stone can therefore only be a pre-existing (pre-fix) world — a deferred migration case,
    // never a fresh-creation opportunity.
    //
    // This type holds those decisions as PURE logic so they are unit-tested under net8 and cannot silently
    // regress. Live geometry (collider bounds, Heightmap height) is supplied BY the engine-bound caller as
    // real numbers — this module never infers geometry from ZDO pivots.
    //
    // net48 audit: System only. Link-compiles into the net8 test project.

    /// <summary>What the event-time realizer should do for a zone whose vanilla host location was just
    /// placed. Stable ordinal — surfaced only as a diagnostic/branch selector, never persisted.</summary>
    public enum LocationRealizationAction
    {
        /// <summary>The just-placed host is not in the deterministic selected set: create nothing.</summary>
        NotSelected = 0,

        /// <summary>The host is selected and a Stone ZDO for its host zone already exists (restart / retry):
        /// reuse it, create nothing. Guarantees exactly one Stone per selected zone.</summary>
        ReuseExisting = 1,

        /// <summary>The host is selected, freshly placed, and has no resident Stone: evaluate the live seat
        /// and create exactly one additive Stone through ghost/full ZNetView init.</summary>
        CreateFresh = 2,
    }

    /// <summary>Whether an ALREADY-GENERATED selected host that is missing its Stone should be force-placed
    /// (never) or reported as a deferred migration. Stable ordinal.</summary>
    public enum ExistingWorldAction
    {
        /// <summary>Nothing to do: the host is not selected, or its Stone is already resident.</summary>
        None = 0,

        /// <summary>The zone was generated by a PRE-FIX world (its one-shot `PlaceLocations` event already
        /// fired and destroyed the live geometry) and the selected host has no Stone. We do NOT guess
        /// geometry from persisted ZDOs; we emit one explicit migration-required diagnostic and preserve a
        /// future migration/provider seam. A disposable fresh world is the supported path for this slice.</summary>
        MigrationRequired = 1,
    }

    /// <summary>Pure event-time realization decision. The engine-bound `PlaceLocations` postfix supplies two
    /// server-owned booleans — is this just-placed host in the selected set, and does a Stone ZDO already
    /// exist for its host zone — and receives the branch to take. No geometry is inferred here.</summary>
    public static class HomesteadStoneLifecycle
    {
        public static LocationRealizationAction DecideEventTime(bool isSelectedHost, bool stoneAlreadyResident)
        {
            if (!isSelectedHost) return LocationRealizationAction.NotSelected;
            if (stoneAlreadyResident) return LocationRealizationAction.ReuseExisting;
            return LocationRealizationAction.CreateFresh;
        }

        /// <summary>Decision for an already-generated zone discovered by the periodic reconcile pass (NOT the
        /// one-shot placement event). A selected host whose zone is already generated but has no Stone can
        /// only be a pre-fix world: report migration-required exactly once, never force a seat.</summary>
        public static ExistingWorldAction DecideExistingWorld(
            bool isSelectedHost, bool zoneAlreadyGenerated, bool stoneAlreadyResident)
        {
            if (!isSelectedHost || stoneAlreadyResident) return ExistingWorldAction.None;
            if (zoneAlreadyGenerated) return ExistingWorldAction.MigrationRequired;
            return ExistingWorldAction.None; // not generated yet → the one-shot event will create it; not a migration.
        }
    }

    /// <summary>Live host-structure geometry captured AT EVENT TIME from the freshly spawned host colliders —
    /// a real world-space axis-aligned XZ bounding box plus the leveled ground height under a probe point.
    /// The engine-bound caller fills these from actual `Collider.bounds` and `Heightmap.GetHeight`, NOT from
    /// ZDO pivots. This struct is the seam that lets the seat scorer stay engine-free and unit-tested.</summary>
    public readonly struct LiveHostBounds
    {
        public LiveHostBounds(double minX, double minZ, double maxX, double maxZ, bool hasBounds)
        {
            MinX = minX;
            MinZ = minZ;
            MaxX = maxX;
            MaxZ = maxZ;
            HasBounds = hasBounds;
        }

        public double MinX { get; }
        public double MinZ { get; }
        public double MaxX { get; }
        public double MaxZ { get; }

        /// <summary>False when no host structural collider was captured this event (degenerate location):
        /// the caller must skip rather than seat against an empty footprint.</summary>
        public bool HasBounds { get; }

        /// <summary>Horizontal distance from a point to this AABB (0 inside), the clearance metric the live
        /// listen-server path already uses. Pure geometry over REAL collider bounds.</summary>
        public double HorizontalClearance(double x, double z)
        {
            var closestX = Clamp(x, MinX, MaxX);
            var closestZ = Clamp(z, MinZ, MaxZ);
            var dx = x - closestX;
            var dz = z - closestZ;
            return Math.Sqrt((dx * dx) + (dz * dz));
        }

        /// <summary>Largest half-extent of the AABB — the readable-yard-band reference the score uses.</summary>
        public double Extent => Math.Max((MaxX - MinX) * 0.5, (MaxZ - MinZ) * 0.5);

        private static double Clamp(double value, double min, double max) =>
            value < min ? min : (value > max ? max : value);
    }

    /// <summary>A deterministic seat reduced to the XZ the pure event-time scorer needs.</summary>
    public readonly struct EventSeat
    {
        public EventSeat(int attempt, double x, double z)
        {
            Attempt = attempt;
            X = x;
            Z = z;
        }

        public int Attempt { get; }
        public double X { get; }
        public double Z { get; }
    }

    /// <summary>A resolved event-time seat: the chosen attempt's XZ and the live-Heightmap ground Y under it.</summary>
    public readonly struct EventSeatResult
    {
        public EventSeatResult(bool hasSeat, int attempt, double x, double z, int attemptsEvaluated)
        {
            HasSeat = hasSeat;
            Attempt = attempt;
            X = x;
            Z = z;
            AttemptsEvaluated = attemptsEvaluated;
        }

        public bool HasSeat { get; }
        public int Attempt { get; }
        public double X { get; }
        public double Z { get; }
        public int AttemptsEvaluated { get; }
    }

    /// <summary>Pure, best-of-eight event-time seat scorer over REAL host-collider bounds. Identical scoring
    /// shape to the prior live <c>SeatEvaluation.Score</c>, but expressed engine-free so BOTH the listen
    /// server (Full) and the headless dedicated server (Ghost) share one unit-tested contract — each now runs
    /// inside the <c>PlaceLocations</c> event where the host colliders and Heightmap are live. The engine-
    /// bound caller resolves each seat's clearance from actual <see cref="LiveHostBounds"/> and supplies the
    /// live ground height; this scorer never touches ZDO pivots.</summary>
    public static class HomesteadEventSeatScorer
    {
        /// <summary>Minimum clearance (m) between the Stone capsule and the host structural AABB.</summary>
        public const double KeepOut = 1.75;

        /// <summary>Score every seat against the live host bounds and pick the best valid one (or none).
        /// A seat is rejected when its live horizontal clearance from the real collider AABB is below
        /// <see cref="KeepOut"/>.</summary>
        public static EventSeatResult ChooseBest(
            System.Collections.Generic.IReadOnlyList<EventSeat> seats,
            LiveHostBounds bounds,
            double hostRadius,
            double hostCenterX,
            double hostCenterZ)
        {
            if (seats == null) throw new ArgumentNullException(nameof(seats));
            if (!bounds.HasBounds)
                return new EventSeatResult(false, -1, 0.0, 0.0, seats.Count);

            var found = false;
            var bestAttempt = -1;
            double bestX = 0.0, bestZ = 0.0;
            var bestScore = double.NegativeInfinity;

            foreach (var seat in seats)
            {
                var clearance = bounds.HorizontalClearance(seat.X, seat.Z);
                if (clearance < KeepOut) continue;
                var radial = Distance(seat.X, seat.Z, hostCenterX, hostCenterZ);
                var score = Score(clearance, radial, hostRadius);
                if (double.IsNegativeInfinity(score)) continue;
                if (!found || score > bestScore || (score.Equals(bestScore) && seat.Attempt < bestAttempt))
                {
                    found = true;
                    bestAttempt = seat.Attempt;
                    bestX = seat.X;
                    bestZ = seat.Z;
                    bestScore = score;
                }
            }

            return new EventSeatResult(found, bestAttempt, bestX, bestZ, seats.Count);
        }

        private static double Score(double clearance, double radialDistance, double hostRadius)
        {
            if (clearance < KeepOut) return double.NegativeInfinity;
            var yardBand = Math.Max(0.0, Math.Min(1.0, 1.0 - (Math.Abs(radialDistance - (hostRadius + 2.5)) / 5.0)));
            return 100.0 + (clearance * 4.0) + (yardBand * 8.0) - (Math.Max(0.0, radialDistance - 12.0) * 2.0);
        }

        private static double Distance(double ax, double az, double bx, double bz)
        {
            var dx = ax - bx;
            var dz = az - bz;
            return Math.Sqrt((dx * dx) + (dz * dz));
        }
    }
}
